language: node_js

cache:
  directories:
    - node_modules

install:
  - npm install --quiet

jobs:
  include:
    - stage: test
      script: npm run test:prod -- --maxWorkers=2 --silent
    - stage: test
      script: npm run tsc
    - stage: test
      script: npm run lint
    - stage: report-cov
      script: npm run report-coverage

notifications:
  email:
    on_success: never
    on_failure: never
